try {
    throw new Error("Gerando um erro genÃªrico!");
} catch (error) {
    console.error(`${error.name}: ${error.message}`);
}